whatbiaspublic/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root             'sources#index'
  get 'users'    => 'static_pages#users'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'sources/approve'   => 'sources#approve'
  patch    'sources/approved'   => 'sources#approved'
  post    'sources/approved'   => 'sources#approved'
  get    'contributors/approve'   => 'contributors#approve'
  patch    'contributors/approved'   => 'contributors#approved'
  post    'contributors/approved'   => 'contributors#approved'

  get    'search/search'   => 'search#search'

  resources :users
  resources :biases
  resources :sources do
    resources :votes, module: :sources
  end
  resources :contributors do
    resources :votes, module: :contributors
  end
  #resources :account_activations, only: [:edit]
  #resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :categories, only: [:show]
end

whatbiaspublic/app/models/contributor.rb
class Contributor < ActiveRecord::Base
  belongs_to :source
  has_many :contributor_categories, dependent: :destroy
  accepts_nested_attributes_for :contributor_categories
  has_many :categories, through: :contributor_categories, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  def should_generate_new_friendly_id?
    name_changed?
  end

  validates :name,  presence: true, uniqueness: { case_sensitive: false }

  mount_uploader :picture, AttachmentUploader
  validates :picture, :presence => true
end

whatbiaspublic/app/controllers/contributors/votes_controller.rb
class Contributors::VotesController < VotesController
  before_action :set_voteable

  private

    def set_voteable
      @voteable = Contributor.friendly.find(params[:contributor_id])
    end
end

whatbiaspublic/app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_action :admin_user,     only: [:destroy, :edit, :approve]

  def index
    @contributors = Contributor.where(:approved => true).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @contributor = Contributor.friendly.find(params[:id])
    if(!@contributor.approved?)
      redirect_to contributors_path
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to contributors_path
  end

  def new
    @contributor = Contributor.new
  end

  def create
    @contributor = Contributor.new(contributor_params)
    if @contributor.save
      if params[:category_ids]
        params[:category_ids].each do |categories|
          categories = ContributorCategory.new(:category_id => categories, :contributor_id => @contributor.id)
          if categories.valid?
            categories.save
          else
            render 'new'
          end
        end
      end

      flash[:success] = "Contributor added, awaiting admin approval."
      redirect_to @contributor
    else
      render 'new'
    end
  end

  def edit
    @contributor = Contributor.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to contributors_path
  end

  def update
    @contributor = Contributor.friendly.find(params[:id])
    if @contributor.update_attributes(contributor_params)
      flash[:success] = "Contributor updated"
      redirect_to @contributor
    else
      render 'edit'
    end
  end

  def destroy
    Contributor.friendly.find(params[:id]).destroy
    flash[:success] = "Contributor deleted"
    redirect_to contributors_approve_path
  end

  def approve
    @contributors = Contributor.where(:approved => false).paginate(:page => params[:page])
  end

  def approved
    @contributor = Contributor.friendly.find(params[:id])
    if current_user && current_user.admin?
      @contributor.update(approved: true)
      flash[:success] = "Contributor approved"
      redirect_to @contributor
    else
      render 'approve'
    end
  end

  private

    def approved_params
      params.require(:contributor).permit(:approved)
    end

    def contributor_params
      params.require(:contributor).permit(:name, :picture, :source_id, category_ids:[])
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user && current_user.admin?
    end
end

whatbiaspublic/app/helpers/contributors_helper.rb
module ContributorsHelper
end

whatbiaspublic/app/views/contributors/_contributor.html.erb
<h1>
  <%= image_tag(contributor.picture_url, alt: contributor.name, class: "contributor_picture") %>
  <%= link_to contributor.name, contributor %>
</h1>

<div class="row">
  <div class="contributor">
    <div class="row">
      <div class="col-md-12">
        <%@category_id = contributor.category_ids.first %>
        <% @biases = Bias.where(category_id: @category_id).sort_by {|b| b.votes.where(voteable_id: contributor.id, voteable_type: "Contributor").count  }.reverse.first(3)%>
        <% @biases.each do |bias|%>
          <%= render partial: "biases/bias", locals: {bias: bias, voteable: contributor} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

whatbiaspublic/app/views/contributors/approve.html.erb
<% provide(:title, 'Unapproved Contributors') %>
<h1>Unapproved Sources</h1>

<%= will_paginate %>

<ul class="contributors">
  <% @contributors.each do |contributor| %>
    <li>
      <%= image_tag(contributor.picture_url, alt: contributor.name, class: "contributor_picture") %>
      <%= link_to contributor.name, contributor %>
      <% if current_user && current_user.admin? %>
        | <%= link_to "Delete", contributor, method: :delete,
                                      data: { confirm: "You sure?" } %>
        | <%= link_to "Approve", contributors_approved_path(id: contributor.friendly_id, approved: true),
                                      method: :post %>
      <% end %>
    </li>
  <% end %>



</ul>

<%= will_paginate %>

whatbiaspublic/app/views/contributors/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit Contributor</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@contributor) do |f| %>
      
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :picture %>
      <%= f.file_field :picture, class: 'form-control' %>
      
      <%= f.submit "Edit Contributor", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

whatbiaspublic/app/views/contributors/index.html.erb
<% provide(:title, 'All Contributors') %>
<h1>All Contributors</h1>

<%= will_paginate %>

<ul class="contributors">
  <%= render @contributors %>
</ul>

<%= will_paginate %>

whatbiaspublic/app/views/contributors/new.html.erb
<% provide(:title, 'Create Contributor') %>
<h1>Create Contributor</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@contributor) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :picture %>
      <%= f.file_field :picture, class: 'form-control' %>

      <%= f.label :source_id %><br />
      <%= f.select :source_id, options_for_select(Source.all.map{|s|[s.name, s.id]}) %>

      <%= f.label :category_id %><br />
      <%= f.select :category_ids, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>

      <%= f.submit "Create Contributor", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

whatbiaspublic/app/views/contributors/show.html.erb
<h1>
  <%= image_tag(@contributor.picture_url, alt: @contributor.name, class: "contributor_picture") %>
  <%= @contributor.name %>
</h1>

<div class="row">
  <div class="col-md-12">
    <% @contributor.category_ids.each do |category_id| %>
      <% @biases = Bias.where(category_id: category_id).sort_by {|b| b.votes.where(voteable_id: @contributor.id, voteable_type: "Contributor").count  }.reverse%>
      <% @biases.each do |bias|%>
        <%= render partial: "biases/bias", locals: {bias: bias, voteable: @contributor} %>
      <% end %>
    <% end %>
  </div>
</div>