whatbiaspublic/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root             'sources#index'
  get 'users'    => 'static_pages#users'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'sources/approve'   => 'sources#approve'
  patch    'sources/approved'   => 'sources#approved'
  post    'sources/approved'   => 'sources#approved'
  get    'contributors/approve'   => 'contributors#approve'
  patch    'contributors/approved'   => 'contributors#approved'
  post    'contributors/approved'   => 'contributors#approved'

  get    'search/search'   => 'search#search'

  resources :users
  resources :biases
  resources :sources do
    resources :votes, module: :sources
  end
  resources :contributors do
    resources :votes, module: :contributors
  end
  #resources :account_activations, only: [:edit]
  #resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :categories, only: [:show]
end

whatbiaspublic/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

whatbiaspublic/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "What Bias", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Politics <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All", {:controller => "categories", :action => "show", :id => "Politics" }%></li>
            <li class="divider"></li>
            <li><%= link_to "Create Source", new_source_path%></li>
            <li class="divider"></li>
            <li><%= link_to "Create Contributor", new_contributor_path%></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Sports <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All", {:controller => "categories", :action => "show", :id => "Sports" }%></li>
            <li class="divider"></li>
            <li><%= link_to "NFL", {:controller => "categories", :action => "show", :id => "NFL" }%></li>
            <li class="divider"></li>
            <li><%= link_to "NBA", {:controller => "categories", :action => "show", :id => "NBA" }%></li>
            <li class="divider"></li>
            <li><%= link_to "MLB", {:controller => "categories", :action => "show", :id => "MLB" }%></li>
            <li class="divider"></li>
            <li><%= link_to "NHL", {:controller => "categories", :action => "show", :id => "NHL" }%></li>
            <li class="divider"></li>
            <li><%= link_to "Create Source", new_source_path%></li>
            <li class="divider"></li>
            <li><%= link_to "Create Contributor", new_contributor_path%></li>
          </ul>
        </li>
      </ul>

      <div class="nav navbar-nav navbar-left">
        <%= form_tag search_search_path, method: :get, class:"navbar-form navbar-right" do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search", class:"form-control" %>
          </div>
          <div class="form-group">
            <%= submit_tag "Search", class:"form-control", :name=>nil %>
          </div>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

whatbiaspublic/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

whatbiaspublic/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html